name: Eco Publish

# on:
#   push:
#     tags:
#       - "*"
on:
  push:
  # release:
  #   types: [published]

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build Project
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Run Tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test
      - name: Publish to NPM
        uses: borales/actions-yarn@v4
        with:
          cmd: prepack && cd build && publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
