name: Eco Publish

on:
  push:
    tags:
      - "*"

# on: [push]
#     tags:
#       - "*"
# on:
#   release:
#     types: [published]

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build Project
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Run Tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ./artifacts
          retention-days: 1
  prepack:
    name: Prepack 
    needs: buildAndTest
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
      - name: Download build artifact from buildAndTest job
        uses: actions/download-artifact@v4
      - name: List Files
        run: ls -R
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      # - name: Build Project
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: build
      # - name: Run Tests
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: test
      - name: Prepack
        uses: borales/actions-yarn@v4
        with:
          cmd: prepack
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: prepackData
          path: |
            ./build
            ./artifacts
          retention-days: 1
  deploy:
    name: Deploy Contracts
    needs: prepack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
      - name: Download build artifact from prepack job
        uses: actions/download-artifact@v4
      - name: List Files
        run: mv ./prepackData/artifacts ./artifacts && mv ./prepackData/build ./build && rm -rf ./prepackData && ls -R
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: versionPackage #need to reset the version to the latest tag or it'll fail to deploy
      # - name: Build Project
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: build
      # - name: Run Tests
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: test
      - name: Deploy Contracts
        uses: borales/actions-yarn@v4
        with:
          cmd: deployCI
        env:
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          OPTIMISM_SCAN_API_KEY: ${{ secrets.OPTIMISM_SCAN_API_KEY }}
          OPTIMISM_BLOCKSCOUT_API_KEY: ${{ secrets.OPTIMISM_BLOCKSCOUT_API_KEY }}
          BASE_SCAN_API_KEY: ${{ secrets.BASE_SCAN_API_KEY }}
          ARBSCAN_API_KEY: ${{ secrets.ARBSCAN_API_KEY }}
          CALDERA_SCAN_API_KEY: ${{ secrets.CALDERA_SCAN_API_KEY }}
          MANTLESCAN_API_KEY: ${{ secrets.MANTLESCAN_API_KEY }}
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            ./build
          retention-days: 1
  publish:
    name: Publish to NPM
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"
      - name: Download build artifact from buildAndTest job
        uses: actions/download-artifact@v4
      - name: List Files
        run: ls -R
      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      # - name: Build Project
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: build
      # - name: Run Tests
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: test
      # - name: Prepack
      #   uses: borales/actions-yarn@v4
      #   with:
      #     cmd: prepack
      - name: Publish to NPM
        uses: borales/actions-yarn@v4
        with:
          cmd: publish # --provenance --access public
          dir: 'build'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
